completed html-relative-links - Trey Dedman
treydedman/c1224-code-solutions pull request #20
Opened 2024-12-17 17:30 UTC by treydedman

2024-12-17 17:35 UTC, treydedman commented
![ss html-relative-links](https://github.com/user-attachments/assets/48192160-12d0-42eb-8b69-6a22fbe204c4)

2024-12-18 17:34 UTC, shawnkost requested changes
Just a few small changes here Trey!

2024-12-18 17:34 UTC, shawnkost commented on html-relative-links/about-me/about-me.html
> +      src="https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
This should be ponting to one of the images we provided for you in the `images` directory

2024-12-18 17:34 UTC, shawnkost commented on html-relative-links/contact-us/contact-us.html
> +      src="https://images.pexels.com/photos/1181295/pexels-photo-1181295.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
This should be ponting to one of the images we provided for you in the `images` directory

2024-12-18 17:34 UTC, shawnkost commented on html-relative-links/index.html
> +      src="https://images.pexels.com/photos/1181703/pexels-photo-1181703.jpeg"
This should be ponting to one of the images we provided for you in the `images` directory

2024-12-18 17:34 UTC, shawnkost commented on html-relative-links/projects/projects.html
> +      src="https://images.pexels.com/photos/6632422/pexels-photo-6632422.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
This should be ponting to one of the images we provided for you in the `images` directory

2024-12-26 14:59 UTC, treydedman commented
updated the pages to link to the included images and attached are screenshots to the 4 html pages 
![ss index](https://github.com/user-attachments/assets/95902a63-3563-4284-842a-56769cd195cd)
![ss about-me](https://github.com/user-attachments/assets/274963d0-7891-41ec-bb95-9e3037a24c2b)
![ss projects](https://github.com/user-attachments/assets/73a1abe6-dbb2-4338-9ed8-b26b0386d0b3)
![ss contact-us](https://github.com/user-attachments/assets/83daefb4-215c-432a-97eb-b2703272291b)

2025-01-06 16:58 UTC, shawnkost approved these changes
👍🏻

2025-01-06 16:59 UTC, shawnkost approved these changes
👍🏻

2025-01-06 17:05 UTC, merged